import { createContext, useContext, useState, useEffect } from 'react';

// Admin-panel UI strings. The customer-facing storefront uses a separate table
// (src/i18n.js); this one only covers the /admin chrome. Some object keys still
// read "drink"/"cafe" for continuity with the shared AdminPage code, but every
// value is grocery wording. Russian is the default; the rest are switchable.
export const adminStrings = {
  ru: {
    panel: 'Админ-панель',
    password: 'Пароль',
    wrongPassword: 'Неверный пароль',
    signIn: 'Войти',
    admin: 'Админ',
    viewMenu: 'Открыть каталог',
    logout: 'Выйти',
    tabDishes: '🥬 Товары',
    tabCategories: '🏷 Категории',
    tabPromotions: '🔥 Акции',
    tabOrders: '🧾 Заказы',
    tabSettings: '⚙️ Настройки',
    tabQr: '🔳 QR',
    new: '+ Создать',
    edit: 'Изменить',
    del: 'Удал.',
    cancel: 'Отмена',
    save: 'Сохранить',
    saved: '✓ Сохранено',
    loading: 'Загрузка…',
    editTitle: 'Изменить',
    newTitle: 'Создать',
    drinks: 'Товары',
    drink: 'товар',
    confirmDeleteDrink: 'Удалить этот товар?',
    hidden: 'скрыт',
    name: 'Название',
    description: 'Описание',
    ingredients: 'Состав (через запятую, по языкам)',
    priceAzn: 'Цена (AZN)',
    category: 'Категория',
    unit: 'Ед. продажи',
    unitNames: { kg: 'кг', piece: 'штука', pack: 'упаковка', bunch: 'пучок' },
    stockQty: 'Остаток',
    stockHint: 'Остаток: пусто — не отслеживается; 0 — нет в наличии.',
    sku: 'Код / артикул',
    calories: 'Калории (100 г)',
    weight: 'Вес (г)',
    sizesOptional: 'Варианты (необязательно)',
    addSize: '+ Вариант',
    noSizes: 'Без вариантов — используется одна цена выше. Добавьте фасовки (1 кг / 5 кг) или виды (с чабрецом, с укропом…).',
    sizeLabelPh: 'Метка (1 кг…)',
    sizeLangToggle: 'Название на каждом языке (для видов: с чабрецом, с укропом…)',
    sizeImageHint: 'Фото варианта',
    sizeTip: 'Совет: держите поле «Цена (AZN)» равным самому дешёвому варианту — оно показывается на карточках и как запасное значение.',
    featured: 'Рекомендуемое ★',
    available: 'Доступно',
    photoOptional: 'Фото (необязательно)',
    removePhoto: 'Удалить фото',
    uploadHint: 'Нажмите, чтобы загрузить фото',
    uploadFormats: 'PNG, JPG — до 5 МБ',
    categories: 'Категории',
    categoryWord: 'категория',
    confirmDeleteCategory: 'Удалить категорию?',
    sortOrder: 'Порядок',
    icon: 'Иконка',
    iconBuiltIn: 'Встроенная',
    iconCustom: 'Своя',
    uploadIcon: 'Загрузить иконку',
    promotions: 'Акции',
    promotionWord: 'акция',
    confirmDeletePromotion: 'Удалить акцию?',
    title: 'Заголовок',
    discount: 'Скидка %',
    orders: 'Заказы',
    noOrders: 'Заказов пока нет.',
    confirmDeleteOrder: 'Удалить этот заказ?',
    confirmDeleteOrders: 'Удалить выбранные заказы?',
    selectAll: 'Выбрать все',
    deleteSelected: 'Удалить выбранные',
    selectOrder: 'Выбрать заказ',
    exportOrders: 'Заказы (Excel)',
    exportSold: 'Продано (Excel)',
    statusNew: 'Новый',
    statusPicking: 'Собирается',
    statusReady: 'Готов',
    statusDone: 'Выдан',
    statusCancelled: 'Отменён',
    filterAll: 'Все',
    dateToday: 'Сегодня',
    dateYesterday: 'Вчера',
    dateMonth: 'Этот месяц',
    dateAll: 'Всё время',
    statOrders: 'Заказы',
    statRevenue: 'Выручка',
    statNew: 'Новые',
    statDelivered: 'Выдано',
    orderNo: 'Заказ',
    cancelConfirm: 'Отменить этот заказ?',
    cancelYes: 'Да, отменить',
    cancelNo: 'Назад',
    newOrderToast: 'Новый заказ',
    pickup: 'Самовывоз',
    delivery: 'Доставка',
    btnAccept: 'Принять',
    btnCancel: 'Отменить',
    btnDeliver: 'Выдан',
    settings: 'Настройки',
    cafeName: 'Название магазина',
    logo: 'Логотип',
    uploadLogo: 'Загрузить логотип',
    logoHint: 'PNG или JPG. Показывается вверху магазина.',
    phone: 'Телефон',
    instagram: 'Instagram',
    deliveryFeeAzn: 'Стоимость доставки (AZN)',
    freeDeliveryOverAzn: 'Бесплатно от (AZN)',
    address: 'Адрес',
    accentColor: 'Акцентный цвет',
    menuUrl: 'URL магазина (для QR)',
    newAdminPassword: 'Новый пароль администратора',
    leaveBlank: 'оставьте пустым',
    whatsapp: 'Номер WhatsApp',
    whatsappHint: 'С кодом страны, напр. +994... — на него приходят заказы.',
    workingHours: 'Часы работы',
    hoursHint: 'Формат «09:00–21:00». Оставьте пустым — день не показывается.',
    saveSettings: 'Сохранить настройки',
    monday: 'Понедельник',
    tuesday: 'Вторник',
    wednesday: 'Среда',
    thursday: 'Четверг',
    friday: 'Пятница',
    saturday: 'Суббота',
    sunday: 'Воскресенье',
    qrCode: 'QR-код',
    qrHint: 'Один QR открывает магазин. Распечатайте его для входа или полок.',
    generate: 'Сгенерировать',
    download: 'Скачать',
  },
  en: {
    panel: 'Admin Panel',
    password: 'Password',
    wrongPassword: 'Wrong password',
    signIn: 'Sign in',
    admin: 'Admin',
    viewMenu: 'View store',
    logout: 'Logout',
    tabDishes: '🥬 Products',
    tabCategories: '🏷 Categories',
    tabPromotions: '🔥 Promotions',
    tabOrders: '🧾 Orders',
    tabSettings: '⚙️ Settings',
    tabQr: '🔳 QR',
    new: '+ New',
    edit: 'Edit',
    del: 'Del',
    cancel: 'Cancel',
    save: 'Save',
    saved: '✓ Saved',
    loading: 'Loading…',
    editTitle: 'Edit',
    newTitle: 'New',
    drinks: 'Products',
    drink: 'product',
    confirmDeleteDrink: 'Delete this product?',
    hidden: 'hidden',
    name: 'Name',
    description: 'Description',
    ingredients: 'Ingredients (comma list per lang)',
    priceAzn: 'Price (AZN)',
    category: 'Category',
    unit: 'Unit of sale',
    unitNames: { kg: 'kg', piece: 'piece', pack: 'pack', bunch: 'bunch' },
    stockQty: 'Stock',
    stockHint: 'Stock: empty = not tracked; 0 = out of stock.',
    sku: 'Code / SKU',
    calories: 'Calories (100 g)',
    weight: 'Weight (g)',
    sizesOptional: 'Variants (optional)',
    addSize: '+ Add variant',
    noSizes: 'No variants — the single price above is used. Add pack sizes (1 kg / 5 kg) or varieties (thyme, dill…).',
    sizeLabelPh: 'Label (1 kg…)',
    sizeLangToggle: 'Name per language (for varieties: thyme, dill…)',
    sizeImageHint: 'Variant photo',
    sizeTip: 'Tip: keep the “Price (AZN)” field equal to the cheapest variant — it’s shown on cards and used as a fallback.',
    featured: 'Featured ★',
    available: 'Available',
    photoOptional: 'Photo (optional)',
    removePhoto: 'Remove photo',
    uploadHint: 'Click to upload a photo',
    uploadFormats: 'PNG, JPG — up to 5 MB',
    categories: 'Categories',
    categoryWord: 'category',
    confirmDeleteCategory: 'Delete category?',
    sortOrder: 'Sort order',
    icon: 'Icon',
    iconBuiltIn: 'Built-in',
    iconCustom: 'Custom',
    uploadIcon: 'Upload icon',
    promotions: 'Promotions',
    promotionWord: 'promotion',
    confirmDeletePromotion: 'Delete promotion?',
    title: 'Title',
    discount: 'Discount %',
    orders: 'Orders',
    noOrders: 'No orders yet.',
    confirmDeleteOrder: 'Delete this order?',
    confirmDeleteOrders: 'Delete the selected orders?',
    selectAll: 'Select all',
    deleteSelected: 'Delete selected',
    selectOrder: 'Select order',
    exportOrders: 'Orders (Excel)',
    exportSold: 'Sold (Excel)',
    statusNew: 'New',
    statusPicking: 'Picking',
    statusReady: 'Ready',
    statusDone: 'Done',
    statusCancelled: 'Cancelled',
    filterAll: 'All',
    dateToday: 'Today',
    dateYesterday: 'Yesterday',
    dateMonth: 'This month',
    dateAll: 'All time',
    statOrders: 'Orders',
    statRevenue: 'Revenue',
    statNew: 'New',
    statDelivered: 'Delivered',
    orderNo: 'Order',
    cancelConfirm: 'Cancel this order?',
    cancelYes: 'Yes, cancel',
    cancelNo: 'Go back',
    newOrderToast: 'New order',
    pickup: 'Pickup',
    delivery: 'Delivery',
    btnAccept: 'Accept',
    btnCancel: 'Cancel',
    btnDeliver: 'Done',
    settings: 'Settings',
    cafeName: 'Store name',
    logo: 'Logo',
    uploadLogo: 'Upload logo',
    logoHint: 'PNG or JPG. Shown at the top of the store.',
    phone: 'Phone',
    instagram: 'Instagram',
    deliveryFeeAzn: 'Delivery fee (AZN)',
    freeDeliveryOverAzn: 'Free delivery over (AZN)',
    address: 'Address',
    accentColor: 'Accent color',
    menuUrl: 'Store URL (for QR)',
    newAdminPassword: 'New admin password',
    leaveBlank: 'leave blank to keep',
    whatsapp: 'WhatsApp number',
    whatsappHint: 'Include country code, e.g. +994... — orders are sent here.',
    workingHours: 'Working hours',
    hoursHint: 'Format “09:00–21:00”. Leave blank to hide a day.',
    saveSettings: 'Save settings',
    monday: 'Monday',
    tuesday: 'Tuesday',
    wednesday: 'Wednesday',
    thursday: 'Thursday',
    friday: 'Friday',
    saturday: 'Saturday',
    sunday: 'Sunday',
    qrCode: 'QR Code',
    qrHint: 'One QR opens the store. Print it for the entrance or the shelves.',
    generate: 'Generate',
    download: 'Download',
  },
  az: {
    panel: 'Admin panel',
    password: 'Şifrə',
    wrongPassword: 'Yanlış şifrə',
    signIn: 'Daxil ol',
    admin: 'Admin',
    viewMenu: 'Kataloqu aç',
    logout: 'Çıxış',
    tabDishes: '🥬 Məhsullar',
    tabCategories: '🏷 Kateqoriyalar',
    tabPromotions: '🔥 Aksiyalar',
    tabOrders: '🧾 Sifarişlər',
    tabSettings: '⚙️ Parametrlər',
    tabQr: '🔳 QR',
    new: '+ Yarat',
    edit: 'Dəyiş',
    del: 'Sil',
    cancel: 'Ləğv et',
    save: 'Yadda saxla',
    saved: '✓ Saxlanıldı',
    loading: 'Yüklənir…',
    editTitle: 'Dəyiş',
    newTitle: 'Yarat',
    drinks: 'Məhsullar',
    drink: 'məhsul',
    confirmDeleteDrink: 'Bu məhsulu silmək?',
    hidden: 'gizli',
    name: 'Ad',
    description: 'Təsvir',
    ingredients: 'Tərkib (vergüllə, dillər üzrə)',
    priceAzn: 'Qiymət (AZN)',
    category: 'Kateqoriya',
    unit: 'Satış vahidi',
    unitNames: { kg: 'kq', piece: 'ədəd', pack: 'paket', bunch: 'dəstə' },
    stockQty: 'Qalıq',
    stockHint: 'Qalıq: boş — izlənmir; 0 — bitib.',
    sku: 'Kod / artikul',
    calories: 'Kalori (100 q)',
    weight: 'Çəki (q)',
    sizesOptional: 'Variantlar (istəyə görə)',
    addSize: '+ Variant',
    noSizes: 'Variant yoxdur — yuxarıdakı tək qiymət istifadə olunur. Qablaşdırma (1 kq / 5 kq) və ya növ (kəklikotulu, şüyüdlü…) əlavə edin.',
    sizeLabelPh: 'Etiket (1 kq…)',
    sizeLangToggle: 'Hər dildə ad (növlər üçün: kəklikotulu, şüyüdlü…)',
    sizeImageHint: 'Variantın şəkli',
    sizeTip: 'Məsləhət: «Qiymət (AZN)» sahəsini ən ucuz varianta bərabər saxlayın — o, kartlarda göstərilir və ehtiyat dəyər kimi istifadə olunur.',
    featured: 'Seçilmiş ★',
    available: 'Mövcuddur',
    photoOptional: 'Şəkil (istəyə görə)',
    removePhoto: 'Şəkli sil',
    uploadHint: 'Şəkil yükləmək üçün klikləyin',
    uploadFormats: 'PNG, JPG — 5 MB-a qədər',
    categories: 'Kateqoriyalar',
    categoryWord: 'kateqoriya',
    confirmDeleteCategory: 'Kateqoriyanı silmək?',
    sortOrder: 'Sıra',
    icon: 'İkon',
    iconBuiltIn: 'Daxili',
    iconCustom: 'Öz',
    uploadIcon: 'İkon yüklə',
    promotions: 'Aksiyalar',
    promotionWord: 'aksiya',
    confirmDeletePromotion: 'Aksiyanı silmək?',
    title: 'Başlıq',
    discount: 'Endirim %',
    orders: 'Sifarişlər',
    noOrders: 'Hələ sifariş yoxdur.',
    confirmDeleteOrder: 'Bu sifarişi silmək?',
    confirmDeleteOrders: 'Seçilmiş sifarişləri silmək?',
    selectAll: 'Hamısını seç',
    deleteSelected: 'Seçilmişləri sil',
    selectOrder: 'Sifarişi seç',
    exportOrders: 'Sifarişlər (Excel)',
    exportSold: 'Satılanlar (Excel)',
    statusNew: 'Yeni',
    statusPicking: 'Yığılır',
    statusReady: 'Hazır',
    statusDone: 'Verildi',
    statusCancelled: 'Ləğv edildi',
    filterAll: 'Hamısı',
    dateToday: 'Bugün',
    dateYesterday: 'Dünən',
    dateMonth: 'Bu ay',
    dateAll: 'Bütün vaxt',
    statOrders: 'Sifariş',
    statRevenue: 'Gəlir',
    statNew: 'Yeni',
    statDelivered: 'Verildi',
    orderNo: 'Sifariş',
    cancelConfirm: 'Bu sifarişi ləğv etmək istəyirsiniz?',
    cancelYes: 'Bəli, ləğv et',
    cancelNo: 'Geri qayıt',
    newOrderToast: 'Yeni sifariş gəldi',
    pickup: 'Özü götürür',
    delivery: 'Çatdırılma',
    btnAccept: 'Qəbul et',
    btnCancel: 'Ləğv et',
    btnDeliver: 'Verildi',
    settings: 'Parametrlər',
    cafeName: 'Mağaza adı',
    logo: 'Logo',
    uploadLogo: 'Logo yüklə',
    logoHint: 'PNG və ya JPG. Mağazanın yuxarısında göstərilir.',
    phone: 'Telefon',
    instagram: 'Instagram',
    deliveryFeeAzn: 'Çatdırılma haqqı (AZN)',
    freeDeliveryOverAzn: 'Pulsuz çatdırılma həddi (AZN)',
    address: 'Ünvan',
    accentColor: 'Vurğu rəngi',
    menuUrl: 'Mağaza URL (QR üçün)',
    newAdminPassword: 'Yeni admin şifrəsi',
    leaveBlank: 'dəyişməmək üçün boş buraxın',
    whatsapp: 'WhatsApp nömrəsi',
    whatsappHint: 'Ölkə kodu ilə, məs. +994... — sifarişlər buraya gəlir.',
    workingHours: 'İş saatları',
    hoursHint: 'Format «09:00–21:00». Boş buraxsanız gün göstərilmir.',
    saveSettings: 'Parametrləri saxla',
    monday: 'Bazar ertəsi',
    tuesday: 'Çərşənbə axşamı',
    wednesday: 'Çərşənbə',
    thursday: 'Cümə axşamı',
    friday: 'Cümə',
    saturday: 'Şənbə',
    sunday: 'Bazar',
    qrCode: 'QR kod',
    qrHint: 'Bir QR mağazanı açır. Giriş və ya rəflər üçün çap edin.',
    generate: 'Yarat',
    download: 'Yüklə',
  },
  tr: {
    panel: 'Yönetim Paneli',
    password: 'Şifre',
    wrongPassword: 'Yanlış şifre',
    signIn: 'Giriş yap',
    admin: 'Yönetim',
    viewMenu: 'Mağazayı aç',
    logout: 'Çıkış',
    tabDishes: '🥬 Ürünler',
    tabCategories: '🏷 Kategoriler',
    tabPromotions: '🔥 Kampanyalar',
    tabOrders: '🧾 Siparişler',
    tabSettings: '⚙️ Ayarlar',
    tabQr: '🔳 QR',
    new: '+ Oluştur',
    edit: 'Düzenle',
    del: 'Sil',
    cancel: 'İptal',
    save: 'Kaydet',
    saved: '✓ Kaydedildi',
    loading: 'Yükleniyor…',
    editTitle: 'Düzenle',
    newTitle: 'Oluştur',
    drinks: 'Ürünler',
    drink: 'ürün',
    confirmDeleteDrink: 'Bu ürün silinsin mi?',
    hidden: 'gizli',
    name: 'Ad',
    description: 'Açıklama',
    ingredients: 'İçindekiler (virgülle, dile göre)',
    priceAzn: 'Fiyat (AZN)',
    category: 'Kategori',
    unit: 'Satış birimi',
    unitNames: { kg: 'kg', piece: 'adet', pack: 'paket', bunch: 'demet' },
    stockQty: 'Stok',
    stockHint: 'Stok: boş — takip edilmiyor; 0 — tükendi.',
    sku: 'Kod / SKU',
    calories: 'Kalori (100 g)',
    weight: 'Ağırlık (g)',
    sizesOptional: 'Varyantlar (isteğe bağlı)',
    addSize: '+ Varyant',
    noSizes: 'Varyant yok — yukarıdaki tek fiyat kullanılır. Paket (1 kg / 5 kg) veya çeşit (kekikli, dereotlu…) ekleyin.',
    sizeLabelPh: 'Etiket (1 kg…)',
    sizeLangToggle: 'Her dilde ad (çeşitler için: kekikli, dereotlu…)',
    sizeImageHint: 'Varyant fotoğrafı',
    sizeTip: 'İpucu: «Fiyat (AZN)» alanını en ucuz varyanta eşit tutun — kartlarda gösterilir ve yedek değer olarak kullanılır.',
    featured: 'Öne çıkan ★',
    available: 'Mevcut',
    photoOptional: 'Fotoğraf (isteğe bağlı)',
    removePhoto: 'Fotoğrafı kaldır',
    uploadHint: 'Fotoğraf yüklemek için tıklayın',
    uploadFormats: 'PNG, JPG — 5 MB’a kadar',
    categories: 'Kategoriler',
    categoryWord: 'kategori',
    confirmDeleteCategory: 'Kategori silinsin mi?',
    sortOrder: 'Sıra',
    icon: 'Simge',
    iconBuiltIn: 'Yerleşik',
    iconCustom: 'Özel',
    uploadIcon: 'Simge yükle',
    promotions: 'Kampanyalar',
    promotionWord: 'kampanya',
    confirmDeletePromotion: 'Kampanya silinsin mi?',
    title: 'Başlık',
    discount: 'İndirim %',
    orders: 'Siparişler',
    noOrders: 'Henüz sipariş yok.',
    confirmDeleteOrder: 'Bu sipariş silinsin mi?',
    confirmDeleteOrders: 'Seçili siparişler silinsin mi?',
    selectAll: 'Tümünü seç',
    deleteSelected: 'Seçilenleri sil',
    selectOrder: 'Siparişi seç',
    exportOrders: 'Siparişler (Excel)',
    exportSold: 'Satılanlar (Excel)',
    statusNew: 'Yeni',
    statusPicking: 'Toplanıyor',
    statusReady: 'Hazır',
    statusDone: 'Teslim edildi',
    statusCancelled: 'İptal edildi',
    filterAll: 'Tümü',
    dateToday: 'Bugün',
    dateYesterday: 'Dün',
    dateMonth: 'Bu ay',
    dateAll: 'Tüm zamanlar',
    statOrders: 'Sipariş',
    statRevenue: 'Gelir',
    statNew: 'Yeni',
    statDelivered: 'Teslim edildi',
    orderNo: 'Sipariş',
    cancelConfirm: 'Bu siparişi iptal etmek istiyor musunuz?',
    cancelYes: 'Evet, iptal et',
    cancelNo: 'Geri dön',
    newOrderToast: 'Yeni sipariş geldi',
    pickup: 'Mağazadan alım',
    delivery: 'Teslimat',
    btnAccept: 'Kabul et',
    btnCancel: 'İptal et',
    btnDeliver: 'Teslim edildi',
    settings: 'Ayarlar',
    cafeName: 'Mağaza adı',
    logo: 'Logo',
    uploadLogo: 'Logo yükle',
    logoHint: 'PNG veya JPG. Mağazanın üstünde gösterilir.',
    phone: 'Telefon',
    instagram: 'Instagram',
    deliveryFeeAzn: 'Teslimat ücreti (AZN)',
    freeDeliveryOverAzn: 'Ücretsiz teslimat limiti (AZN)',
    address: 'Adres',
    accentColor: 'Vurgu rengi',
    menuUrl: 'Mağaza URL (QR için)',
    newAdminPassword: 'Yeni yönetici şifresi',
    leaveBlank: 'değiştirmemek için boş bırakın',
    whatsapp: 'WhatsApp numarası',
    whatsappHint: 'Ülke koduyla, örn. +994... — siparişler buraya gelir.',
    workingHours: 'Çalışma saatleri',
    hoursHint: 'Format “09:00–21:00”. Boş bırakırsanız gün gösterilmez.',
    saveSettings: 'Ayarları kaydet',
    monday: 'Pazartesi',
    tuesday: 'Salı',
    wednesday: 'Çarşamba',
    thursday: 'Perşembe',
    friday: 'Cuma',
    saturday: 'Cumartesi',
    sunday: 'Pazar',
    qrCode: 'QR Kodu',
    qrHint: 'Tek bir QR mağazayı açar. Giriş veya raflar için yazdırın.',
    generate: 'Oluştur',
    download: 'İndir',
  },
};

// Languages the admin chrome can be displayed in (order = cycle order in the
// header switcher). Matches the customer-facing LANGUAGES set in i18n.js.
export const ADMIN_LANG_CODES = Object.keys(adminStrings);

const AdminLangContext = createContext({ lang: 'ru', setLang: () => {}, t: adminStrings.ru });

export function AdminLangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('admin_lang') || 'ru');
  useEffect(() => { localStorage.setItem('admin_lang', lang); }, [lang]);
  const value = { lang, setLang, t: adminStrings[lang] || adminStrings.ru };
  return <AdminLangContext.Provider value={value}>{children}</AdminLangContext.Provider>;
}

export function useAdminLang() {
  return useContext(AdminLangContext);
}
